### ISSUE TITLE
Добавить функцию копирования реквизитов

### ISSUE THREAD

**Issue by HotFixDeveloper** [nezavisimost/liberty-ios#17]
### Description

Было бы неплохо, если бы, нажимая на определенный блок с реквизитом для доната - выскакивало окошко "Скопировано!", ну и соотвественно реквизит бы копировался. А то пока он просто есть, и его нужно как-то вручную переписывать.

**Comment by felstell** [comment]
Добавил. Войдет в следующий апдейт
