### ISSUE TITLE
[BUG]: Кнопки в разделе "About"

### ISSUE THREAD

**Issue by HotFixDeveloper** [nezavisimost/liberty-ios#20]
### Description of the bug

Кнопки на соц. сети FuckRKN1 в разделе "About" ничего не открывают и никуда не ведут. 

### Steps To Reproduce

1. Открыть приложение FuckRKN
2. Нажать на "About" 
3. Проскролить вниз 
4. Попробовать выбрать любую соц. сеть

**Comment by felstell** [comment]
Fixed in PR https://github.com/nezavisimost/liberty-ios/pull/24
